"""Training provider abstractions for telemetry LLM fine-tuning."""

from __future__ import annotations

import asyncio
from asyncio.subprocess import Process
import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from ..telemetry_prompt_dataset_builder import (
	TelemetryPromptDatasetBuilder,
	DatasetBuildStats,
)
from .prompt_response_example import PromptResponseExample


@dataclass
class LLMTrainingContext:
	"""Context shared with all training providers for a single run.
		output_root: is the base directory where providers should write their datasets.
  	"""

	dataset_id: str
	segments_cache_key: str
	output_root: Path
	data_caching_service: Any
	annotations: Optional[Dict[str, Dict[str, Any]]] = None
	shuffle: bool = True
	metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LLMTrainingContribution:
	"""Dataset artifact generated by a training provider."""

	provider_name: str
	dataset_path: Path
	stats: Dict[str, Any] = field(default_factory=dict)
	metadata: Dict[str, Any] = field(default_factory=dict)
	cleanup: bool = True
@dataclass
class AnnotationSessionArtifacts:
	"""Container for files that coordinate annotation sessions."""

	dataset_path: Path
	annotation_path: Path
	session_dir: Path
	builder_stats: DatasetBuildStats
	random_seed: int


class BaseLLMTrainingProvider:
	"""Interface for providers contributing prompt/response samples."""

	name: str = "base_provider"

	async def produce(self, context: LLMTrainingContext) -> Optional[LLMTrainingContribution]:
		"""Generates a dataset contribution based on the provided context."""
		raise NotImplementedError


class SegmentExplanationTrainingProvider(BaseLLMTrainingProvider):
	"""Coordinates guided telemetry annotation sessions for segment explanations."""

	name = "segment_explanation"

	ANNOTATION_SUFFIX = ".annotations.jsonl"

	def __init__(self, builder: TelemetryPromptDatasetBuilder) -> None:
		self._builder = builder

	async def produce(self, context: LLMTrainingContext) -> Optional[LLMTrainingContribution]:
		"""Orchestrate a guided annotation session and return the annotated dataset."""

		if not context.segments_cache_key:
			raise RuntimeError("segments_cache_key is required to prepare telemetry samples for annotation")

		session = await asyncio.to_thread(self._create_annotation_session, context)
		print(
			f"\n[INFO] Prepared annotation dataset ({session.builder_stats.windows_kept} windows) at {session.dataset_path}"
		)

		process = await self._launch_annotation_app(session)
		try:
			await self._await_session_completion(session, process)
		except Exception:
			await self._terminate_process(process)
			raise
		else:
			await self._terminate_process(process)

		annotated_dataset_path, annotated_ids = await asyncio.to_thread(
			self._collect_annotated_dataset,
			session,
		)

		annotation_summary = await asyncio.to_thread(
			self._read_annotation_statistics,
			session.dataset_path,
			session.annotation_path,
		)

		annotated_examples = annotation_summary.get("annotated_examples", 0)
		if annotated_examples == 0:
			raise RuntimeError("Guided annotation session produced no annotated windows. Cannot continue with training.")

		stats_dict = {
			"provider": self.name,
			"total_examples": annotation_summary.get("total_examples", 0),
			"annotated_examples": annotated_examples,
			"annotation_coverage": annotation_summary.get("annotation_coverage", 0.0),
			"output_path": str(annotated_dataset_path),
			"builder_stats": session.builder_stats.to_dict(),
			"annotation_session_seed": session.random_seed,
		}

		return LLMTrainingContribution(
			provider_name=self.name,
			dataset_path=annotated_dataset_path,
			stats=stats_dict,
			metadata={
				"builder": "telemetry_segments",
				"annotations": annotation_summary,
				"sample_dataset_path": str(session.dataset_path),
				"selected_window_ids": annotated_ids,
			},
		)


	def _read_annotation_statistics(self, dataset_path: Path, annotation_path: Path) -> Dict[str, Any]:
		"""Read annotation statistics from the dataset after manual annotation."""
		total_examples = 0
		annotated_examples = 0
		pending_examples = 0
		
		if not dataset_path.exists():
			return {
				"annotation_path": None,
				"annotation_store_found": False,
				"annotations_available": 0,
				"annotations_applied": 0,
				"total_examples": 0,
				"annotated_examples": 0,
				"pending_examples": 0,
				"annotation_coverage": 0.0,
			}
		
		with dataset_path.open("r", encoding="utf-8") as dataset_file:
			for line in dataset_file:
				line = line.strip()
				if not line:
					continue
				try:
					record = json.loads(line)
					example = PromptResponseExample.from_record(record)
				except (json.JSONDecodeError, ValueError, TypeError):
					continue
				
				metadata = example.metadata or {}
				is_annotated = metadata.get("annotation_complete", False)
				if is_annotated:
					annotated_examples += 1
				else:
					pending_examples += 1
				total_examples += 1
		
		# Count annotations from the annotation store
		annotations_count = 0
		if annotation_path.exists():
			with annotation_path.open("r", encoding="utf-8") as annotation_file:
				for line in annotation_file:
					line = line.strip()
					if not line:
						continue
					try:
						json.loads(line)  # Just validate it's valid JSON
						annotations_count += 1
					except json.JSONDecodeError:
						continue
		
		return {
			"annotation_path": str(annotation_path) if annotation_path.exists() else None,
			"annotation_store_found": annotation_path.exists(),
			"annotations_available": annotations_count,
			"annotations_applied": annotated_examples,
			"total_examples": total_examples,
			"annotated_examples": annotated_examples,
			"pending_examples": pending_examples,
			"annotation_coverage": (annotated_examples / total_examples) if total_examples else 0.0,
		}

	def _create_annotation_session(self, context: LLMTrainingContext) -> AnnotationSessionArtifacts:
		output_dir = context.output_root / self.name
		output_dir.mkdir(parents=True, exist_ok=True)

		session_dir = output_dir / f"{context.dataset_id}_{self.name}_session"
		session_dir.mkdir(parents=True, exist_ok=True)

		dataset_filename = f"{context.dataset_id}_{self.name}_sample.jsonl"
		sample_dataset_path = session_dir / dataset_filename
		annotation_path = session_dir / f"{dataset_filename}{self.ANNOTATION_SUFFIX}"

		for path in (sample_dataset_path, annotation_path):
			path.unlink(missing_ok=True)

		annotation_path.parent.mkdir(parents=True, exist_ok=True)
		annotation_path.touch()

		metadata = context.metadata or {}

		raw_sample_size = metadata.get("annotation_sample_size", 25)
		try:
			sample_size = int(raw_sample_size)
		except (TypeError, ValueError):
			sample_size = 25
		sample_size = max(1, sample_size)

		raw_seed = metadata.get("annotation_random_seed")
		if raw_seed is None:
			raw_seed = int(datetime.utcnow().timestamp() * 1000)
		try:
			random_seed = int(raw_seed)
		except (TypeError, ValueError):
			random_seed = int(datetime.utcnow().timestamp() * 1000)

		original_max_examples = self._builder.config.max_examples
		original_rng_state = getattr(self._builder._rng, "getstate", lambda: None)()

		try:
			self._builder.config.max_examples = sample_size
			if hasattr(self._builder._rng, "seed"):
				self._builder._rng.seed(random_seed)
			records, stats = self._builder.build_from_cached_segments(
				segments_cache_key=context.segments_cache_key,
				shuffle=True,
			)
		finally:
			self._builder.config.max_examples = original_max_examples
			if original_rng_state is not None and hasattr(self._builder._rng, "setstate"):
				self._builder._rng.setstate(original_rng_state)

		if not records:
			raise RuntimeError("No telemetry windows were generated for annotation. Ensure cached segments are available.")

		record_count = 0
		window_id_found = False
		with sample_dataset_path.open("w", encoding="utf-8") as handle:
			for example in records:
				metadata = example.metadata or {}
				if not isinstance(metadata, dict):
					metadata = {}
				window_id = metadata.get("window_id")
				if isinstance(window_id, str) and window_id:
					window_id_found = True
				handle.write(
					json.dumps(
						example.to_record(),
						ensure_ascii=False,
						default=self._builder._json_default,  # type: ignore[attr-defined]
					)
					+ "\n"
				)
				record_count += 1

		if record_count == 0:
			raise RuntimeError("Telemetry dataset write produced no records; aborting annotation session.")
		if not window_id_found:
			raise RuntimeError("Telemetry records are missing window IDs; cannot launch annotation session.")

		return AnnotationSessionArtifacts(
			dataset_path=sample_dataset_path.resolve(),
			annotation_path=annotation_path.resolve(),
			session_dir=session_dir.resolve(),
			builder_stats=stats,
			random_seed=random_seed,
		)

	async def _launch_annotation_app(self, session: AnnotationSessionArtifacts) -> Process:
		"""Launch the annotation app in a subprocess."""
		script_path = Path(__file__).resolve().parents[3] / "ui" / "telemetry_prompt_annotation_app.py"
		if not script_path.exists():
			raise RuntimeError(f"Annotation UI script not found at {script_path}")

		env = os.environ.copy()
		env.setdefault("STREAMLIT_BROWSER_GATHER_USAGE_STATS", "false")
		env["ANNOTATION_DATASET_PATH"] = str(session.dataset_path)
		env["ANNOTATION_DATASET_DIR"] = str(session.dataset_path.parent)

		print(f"[INFO] Launching Streamlit annotation UI for {session.dataset_path}")

		# Launch using streamlit run command
		return await asyncio.create_subprocess_exec(
			sys.executable,
			"-m",
			"streamlit",
			"run",
			str(script_path),
			"--server.headless=true",
			cwd=str(script_path.parent),
			env=env,
		)

	async def _await_session_completion(
		self,
		session: AnnotationSessionArtifacts,
		process: Process,
	) -> None:
		print("[INFO] Waiting for annotation UI to close. Close the browser/app when finished annotating.")
		returncode = await process.wait()
		if returncode not in (0, None):
			print(f"[WARNING] Annotation UI exited with status: {returncode}")

	async def _terminate_process(self, process: Process) -> None:
		if process.returncode is not None:
			return

		try:
			process.terminate()
		except ProcessLookupError:
			return
		except Exception:
			try:
				process.kill()
				await process.wait()
			except Exception:
				pass
			return

		try:
			await asyncio.wait_for(process.wait(), timeout=5)
		except asyncio.TimeoutError:
			try:
				process.kill()
				await process.wait()
			except Exception:
				pass

	def _collect_annotated_dataset(
		self,
		session: AnnotationSessionArtifacts,
	) -> Tuple[Path, List[str]]:
		annotated_examples: List[PromptResponseExample] = []
		annotated_ids: List[str] = []
		with session.dataset_path.open("r", encoding="utf-8") as handle:
			for raw_line in handle:
				line = raw_line.strip()
				if not line:
					continue
				try:
					record = json.loads(line)
					example = PromptResponseExample.from_record(record)
				except (json.JSONDecodeError, ValueError, TypeError):
					continue

				metadata = example.metadata or {}
				window_id = metadata.get("window_id")
				if not isinstance(window_id, str) or not window_id:
					continue

				if metadata.get("annotation_complete"):
					annotated_examples.append(example)
					annotated_ids.append(window_id)

		if not annotated_examples:
			raise RuntimeError("No annotated windows were found in the dataset after the session completed.")

		annotated_ids = list(dict.fromkeys(annotated_ids))

		annotated_dataset_path = session.session_dir / f"{session.dataset_path.stem}_annotated.jsonl"
		annotated_dataset_path.unlink(missing_ok=True)

		with annotated_dataset_path.open("w", encoding="utf-8") as handle:
			for example in annotated_examples:
				handle.write(
					json.dumps(
						example.to_record(),
						ensure_ascii=False,
						default=self._builder._json_default,  # type: ignore[attr-defined]
					)
					+ "\n"
				)

		return annotated_dataset_path, annotated_ids


class TransformerDirectiveTrainingProvider(BaseLLMTrainingProvider):
	"""Generates samples that teach the LLM how to delegate to the transformer model."""

	name = "transformer_directive"

	def __init__(
		self,
		builder: TelemetryPromptDatasetBuilder,
		*,
		max_samples: int = 1500,
	) -> None:
		self._builder = builder
		self._max_samples = max_samples
		self._system_prompt = (
			"You are an elite telemetry strategist. When a segment requires fine-grained action "
			"planning, wrap the transformer invocation in the response so downstream services can "
			"delegate execution. Always include a concise coaching summary alongside the directive."
		)

	async def produce(self, context: LLMTrainingContext) -> Optional[LLMTrainingContribution]:
		if not context.segments_cache_key:
			return None

		output_dir = context.output_root / self.name
		output_dir.mkdir(parents=True, exist_ok=True)
		dataset_path = output_dir / f"{context.dataset_id}_{self.name}.jsonl"

		total_examples = 0
		segments_considered = 0

		def _generate_examples() -> None:
			nonlocal total_examples, segments_considered

			with dataset_path.open("w", encoding="utf-8") as handle:
				chunk_iterator = context.data_caching_service.get_cached_data_chunks(
					cache_key=context.segments_cache_key
				)
				prediction_steps = self._builder.config.prediction_steps

				for chunk_data in chunk_iterator:
					# chunk_data is a list of segments (List[List[Dict[str, Any]]])
					if chunk_data is None or not chunk_data:
						continue
					
					# Ensure chunk_data is a list
					if not isinstance(chunk_data, list):
						continue

					for segment in chunk_data:
						segments_considered += 1
						# segment is a list of telemetry dictionaries
						if not segment or not isinstance(segment, list):
							continue
						
						if len(segment) < self._builder.config.context_steps:
							continue

						context_slice = segment[: self._builder.config.context_steps]
						if not context_slice:
							continue

						future_slice = segment[
							self._builder.config.context_steps : self._builder.config.context_steps + prediction_steps
						]
						directive = self._build_directive(
							context_slice,
							future_slice,
							context.metadata,
						)
						example = self._build_entry(
							context_slice,
							directive,
							prediction_steps,
							context.metadata,
						)
						handle.write(
							json.dumps(
								example.to_record(),
								ensure_ascii=False,
								default=self._builder._json_default,  # type: ignore[attr-defined]
							)
							+ "\n"
						)
						total_examples += 1

						if self._max_samples and total_examples >= self._max_samples:
							return

		await asyncio.to_thread(_generate_examples)

		if total_examples == 0:
			dataset_path.unlink(missing_ok=True)
			return None

		stats = {
			"provider": self.name,
			"total_examples": total_examples,
			"segments_considered": segments_considered,
			"output_path": str(dataset_path),
		}

		return LLMTrainingContribution(
			provider_name=self.name,
			dataset_path=dataset_path,
			stats=stats,
			metadata={
				"directive": "transformer",
				"segments_considered": segments_considered,
			},
		)

	def _build_directive(
		self,
		context_window: Any,
		future_slice: Any,
		metadata: Dict[str, Any],
	) -> Dict[str, Any]:
		control_features = ("Physics_gas", "Physics_brake", "Physics_steer_angle", "Physics_gear")

		max_brake = max((step.get("Physics_brake", 0.0) or 0.0) for step in context_window)
		max_gas = max((step.get("Physics_gas", 0.0) or 0.0) for step in context_window)
		steer_variance = self._variance([step.get("Physics_steer_angle", 0.0) or 0.0 for step in context_window])
		speed_values = [step.get("Physics_speed_kmh", 0.0) or 0.0 for step in context_window]
		speed_drop = max(speed_values) - min(speed_values) if speed_values else 0.0

		if max_brake > 0.7 and speed_drop > 20:
			reason = "Heavy braking zone detected – delegate precise deceleration plan to transformer."
		elif steer_variance > 100:
			reason = "Rapid steering oscillations – transformer should compute fine-grained steering sequence."
		elif max_gas > 0.95 and speed_drop < 5:
			reason = "Flat-out acceleration – transformer can optimise throttle modulation to avoid wheel spin."
		else:
			reason = "Mixed-control segment – transformer needed for coordinated pedal and steering adjustments."

		directive = {
			"model": "expert_action_transformer",
			"reason": reason,
			"expected_outputs": list(control_features),
			"future_hint": future_slice[:1] if future_slice else [],
			"metadata": metadata or {},
		}
		return directive

	def _build_entry(
		self,
		context_window: Any,
		directive: Dict[str, Any],
		prediction_steps: int,
		metadata: Dict[str, Any],
	) -> PromptResponseExample:
		user_prompt = (
			"Task: Review the telemetry segment and respond with a JSON object that contains a coaching summary "
			"and a `transformer_directive`. Use the directive to describe how the ExpertActionTransformer should "
			"be invoked for high-resolution planning. Include any crucial parameters it must receive.\n\n"
			"Telemetry context (ordered timesteps):\n"
			f"{json.dumps(context_window, indent=2, ensure_ascii=False)}\n\n"
			f"Future horizon hint ({prediction_steps} steps available): {prediction_steps}"
		)

		assistant_payload = {
			"coaching_summary": directive["reason"],
			"transformer_directive": {
				"action": "invoke",
				"model": directive["model"],
				"inputs": {
					"reuse_context_window": True,
					"expected_outputs": directive["expected_outputs"],
					"future_hint": directive.get("future_hint", []),
				},
				"metadata": directive.get("metadata", {}),
			},
		}

		return PromptResponseExample(
			prompt=user_prompt,
			response=json.dumps(assistant_payload, ensure_ascii=False),
			system_prompt=self._system_prompt,
			metadata={
				"provider": self.name,
				"prediction_steps": prediction_steps,
				"source": metadata,
			},
		)

	@staticmethod
	def _variance(values: Any) -> float:
		if not values:
			return 0.0
		mean = sum(values) / len(values)
		return float(sum((value - mean) ** 2 for value in values) / len(values))


__all__ = [
	"LLMTrainingContext",
	"LLMTrainingContribution",
	"BaseLLMTrainingProvider",
	"SegmentExplanationTrainingProvider",
	"TransformerDirectiveTrainingProvider",
	"PromptResponseExample",
]
