"""Training provider abstractions for telemetry LLM fine-tuning."""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from ..telemetry_prompt_dataset_builder import (
	TelemetryPromptDatasetBuilder,
	DatasetBuildStats,
)
from .prompt_response_example import PromptResponseExample


@dataclass
class LLMTrainingContext:
	"""Context shared with all training providers for a single run.
		output_root: is the base directory where providers should write their datasets.
  	"""

	dataset_id: str
	segments_cache_key: str
	output_root: Path
	data_caching_service: Any
	annotations: Optional[Dict[str, Dict[str, Any]]] = None
	shuffle: bool = True
	metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LLMTrainingContribution:
	"""Dataset artifact generated by a training provider."""

	provider_name: str
	dataset_path: Path
	stats: Dict[str, Any] = field(default_factory=dict)
	metadata: Dict[str, Any] = field(default_factory=dict)
	cleanup: bool = True
@dataclass
class AnnotationSessionArtifacts:
	"""Container for files that coordinate annotation sessions."""

	dataset_path: Path
	annotation_path: Path
	builder_stats: DatasetBuildStats
	random_seed: int


class BaseLLMTrainingProvider:
	"""Interface for providers contributing prompt/response samples."""

	name: str = "base_provider"

	async def produce(self, context: LLMTrainingContext) -> Optional[LLMTrainingContribution]:
		"""Generates a dataset contribution based on the provided context."""
		raise NotImplementedError


class SegmentExplanationTrainingProvider(BaseLLMTrainingProvider):
	"""Coordinates guided telemetry annotation sessions for segment explanations."""

	name = "segment_explanation"

	ANNOTATION_SUFFIX = ".annotations.jsonl"

	def __init__(self, builder: TelemetryPromptDatasetBuilder) -> None:
		self._builder = builder

	async def produce(self, context: LLMTrainingContext) -> Optional[LLMTrainingContribution]:
		"""Orchestrate a guided annotation session and return the annotated dataset."""

		if not context.segments_cache_key:
			raise RuntimeError("segments_cache_key is required to prepare telemetry samples for annotation")

		metadata = context.metadata or {}
		sample_size = int(metadata.get("annotation_sample_size", 25))
		random_seed = int(metadata.get("annotation_random_seed", 0)) or int(datetime.utcnow().timestamp() * 1000)

		original_max_examples = self._builder.config.max_examples
		original_rng_state = getattr(self._builder._rng, "getstate", lambda: None)()

		try:
			self._builder.config.max_examples = sample_size
			if hasattr(self._builder._rng, "seed"):
				self._builder._rng.seed(random_seed)
			records, stats = self._builder.build_from_cached_segments(
				segments_cache_key=context.segments_cache_key,
				shuffle=True,
			)
		finally:
			self._builder.config.max_examples = original_max_examples
			if original_rng_state is not None and hasattr(self._builder._rng, "setstate"):
				self._builder._rng.setstate(original_rng_state)

		if not records:
			raise RuntimeError("No telemetry windows were generated for annotation. Ensure cached segments are available.")

		session = await asyncio.to_thread(self._create_annotation_dataset, context, records)
		print(
			f"\n[INFO] Prepared annotation dataset ({stats.windows_kept} windows) at {session.dataset_path}"
		)

		stats_dict = {
			"provider": self.name,
			"total_examples": stats.windows_kept,
			"annotated_examples": 0,
			"annotation_coverage": 0.0,
			"output_path": str(session.dataset_path),
			"builder_stats": stats.to_dict(),
			"annotation_session_seed": session.random_seed,
		}

		return LLMTrainingContribution(
			provider_name=self.name,
			dataset_path=session.dataset_path,
			stats=stats_dict,
			metadata={
				"builder": "telemetry_segments",
				"sample_dataset_path": str(session.dataset_path),
			},
			cleanup=False,
		)

	def _read_annotation_statistics(self, dataset_path: Path, annotation_path: Path) -> Dict[str, Any]:
		"""Read annotation statistics from the dataset after manual annotation."""
		total_examples = 0
		annotated_examples = 0
		pending_examples = 0
		
		if not dataset_path.exists():
			return {
				"annotation_path": None,
				"annotation_store_found": False,
				"annotations_available": 0,
				"annotations_applied": 0,
				"total_examples": 0,
				"annotated_examples": 0,
				"pending_examples": 0,
				"annotation_coverage": 0.0,
			}
		
		with dataset_path.open("r", encoding="utf-8") as dataset_file:
			for line in dataset_file:
				line = line.strip()
				if not line:
					continue
				try:
					record = json.loads(line)
					example = PromptResponseExample.from_record(record)
				except (json.JSONDecodeError, ValueError, TypeError):
					continue
				
				metadata = example.metadata or {}
				is_annotated = metadata.get("annotation_complete", False)
				if is_annotated:
					annotated_examples += 1
				else:
					pending_examples += 1
				total_examples += 1
		
		# Count annotations from the annotation store
		annotations_count = 0
		if annotation_path.exists():
			with annotation_path.open("r", encoding="utf-8") as annotation_file:
				for line in annotation_file:
					line = line.strip()
					if not line:
						continue
					try:
						json.loads(line)  # Just validate it's valid JSON
						annotations_count += 1
					except json.JSONDecodeError:
						continue
		
		return {
			"annotation_path": str(annotation_path) if annotation_path.exists() else None,
			"annotation_store_found": annotation_path.exists(),
			"annotations_available": annotations_count,
			"annotations_applied": annotated_examples,
			"total_examples": total_examples,
			"annotated_examples": annotated_examples,
			"pending_examples": pending_examples,
			"annotation_coverage": (annotated_examples / total_examples) if total_examples else 0.0,
		}

	def _create_annotation_dataset(
		self,
		context: LLMTrainingContext,
		records: List[PromptResponseExample],
	) -> AnnotationSessionArtifacts:
		output_dir = context.output_root / self.name
		output_dir.mkdir(parents=True, exist_ok=True)

		dataset_filename = f"{context.dataset_id}_{self.name}_sample.jsonl"
		sample_dataset_path = output_dir / dataset_filename
		annotation_path = output_dir / f"{dataset_filename}{self.ANNOTATION_SUFFIX}"

		for path in (sample_dataset_path, annotation_path):
			path.unlink(missing_ok=True)

		annotation_path.parent.mkdir(parents=True, exist_ok=True)
		annotation_path.touch()

		metadata = context.metadata or {}
		raw_seed = metadata.get("annotation_random_seed")
		random_seed = int(raw_seed) if raw_seed else int(datetime.utcnow().timestamp() * 1000)

		if not records:
			raise RuntimeError("No telemetry windows were provided for annotation.")

		with sample_dataset_path.open("w", encoding="utf-8") as handle:
			for example in records:
				handle.write(
					json.dumps(
						example.to_record(),
						ensure_ascii=False,
						default=self._builder._json_default,
					)
					+ "\n"
				)

		return AnnotationSessionArtifacts(
			dataset_path=sample_dataset_path.resolve(),
			annotation_path=annotation_path.resolve(),
			builder_stats=DatasetBuildStats(windows_kept=len(records)),
			random_seed=random_seed,
		)



class TransformerDirectiveTrainingProvider(BaseLLMTrainingProvider):
	"""Generates samples that teach the LLM how to delegate to the transformer model."""

	name = "transformer_directive"

	def __init__(
		self,
		builder: TelemetryPromptDatasetBuilder,
		*,
		max_samples: int = 1500,
	) -> None:
		self._builder = builder
		self._max_samples = max_samples
		self._system_prompt = (
			"You are an elite telemetry strategist. When a segment requires fine-grained action "
			"planning, wrap the transformer invocation in the response so downstream services can "
			"delegate execution. Always include a concise coaching summary alongside the directive."
		)

	async def produce(self, context: LLMTrainingContext) -> Optional[LLMTrainingContribution]:
		if not context.segments_cache_key:
			return None

		output_dir = context.output_root / self.name
		output_dir.mkdir(parents=True, exist_ok=True)
		dataset_path = output_dir / f"{context.dataset_id}_{self.name}.jsonl"

		total_examples = 0
		segments_considered = 0

		def _generate_examples() -> None:
			nonlocal total_examples, segments_considered

			with dataset_path.open("w", encoding="utf-8") as handle:
				chunk_iterator = context.data_caching_service.get_cached_data_chunks(
					cache_key=context.segments_cache_key
				)
				prediction_steps = self._builder.config.prediction_steps

				for chunk_data in chunk_iterator:
					# chunk_data is a list of segments (List[List[Dict[str, Any]]])
					if chunk_data is None or not chunk_data:
						continue
					
					# Ensure chunk_data is a list
					if not isinstance(chunk_data, list):
						continue

					for segment in chunk_data:
						segments_considered += 1
						# segment is a list of telemetry dictionaries
						if not segment or not isinstance(segment, list):
							continue
						
						if len(segment) < self._builder.config.context_steps:
							continue

						context_slice = segment[: self._builder.config.context_steps]
						if not context_slice:
							continue

						future_slice = segment[
							self._builder.config.context_steps : self._builder.config.context_steps + prediction_steps
						]
						directive = self._build_directive(
							context_slice,
							future_slice,
							context.metadata,
						)
						example = self._build_entry(
							context_slice,
							directive,
							prediction_steps,
							context.metadata,
						)
						handle.write(
							json.dumps(
								example.to_record(),
								ensure_ascii=False,
								default=self._builder._json_default,  # type: ignore[attr-defined]
							)
							+ "\n"
						)
						total_examples += 1

						if self._max_samples and total_examples >= self._max_samples:
							return

		await asyncio.to_thread(_generate_examples)

		if total_examples == 0:
			dataset_path.unlink(missing_ok=True)
			return None

		stats = {
			"provider": self.name,
			"total_examples": total_examples,
			"segments_considered": segments_considered,
			"output_path": str(dataset_path),
		}

		return LLMTrainingContribution(
			provider_name=self.name,
			dataset_path=dataset_path,
			stats=stats,
			metadata={
				"directive": "transformer",
				"segments_considered": segments_considered,
			},
		)

	def _build_directive(
		self,
		context_window: Any,
		future_slice: Any,
		metadata: Dict[str, Any],
	) -> Dict[str, Any]:
		control_features = ("Physics_gas", "Physics_brake", "Physics_steer_angle", "Physics_gear")

		max_brake = max((step.get("Physics_brake", 0.0) or 0.0) for step in context_window)
		max_gas = max((step.get("Physics_gas", 0.0) or 0.0) for step in context_window)
		steer_variance = self._variance([step.get("Physics_steer_angle", 0.0) or 0.0 for step in context_window])
		speed_values = [step.get("Physics_speed_kmh", 0.0) or 0.0 for step in context_window]
		speed_drop = max(speed_values) - min(speed_values) if speed_values else 0.0

		if max_brake > 0.7 and speed_drop > 20:
			reason = "Heavy braking zone detected – delegate precise deceleration plan to transformer."
		elif steer_variance > 100:
			reason = "Rapid steering oscillations – transformer should compute fine-grained steering sequence."
		elif max_gas > 0.95 and speed_drop < 5:
			reason = "Flat-out acceleration – transformer can optimise throttle modulation to avoid wheel spin."
		else:
			reason = "Mixed-control segment – transformer needed for coordinated pedal and steering adjustments."

		directive = {
			"model": "expert_action_transformer",
			"reason": reason,
			"expected_outputs": list(control_features),
			"future_hint": future_slice[:1] if future_slice else [],
			"metadata": metadata or {},
		}
		return directive

	def _build_entry(
		self,
		context_window: Any,
		directive: Dict[str, Any],
		prediction_steps: int,
		metadata: Dict[str, Any],
	) -> PromptResponseExample:
		user_prompt = (
			"Task: Review the telemetry segment and respond with a JSON object that contains a coaching summary "
			"and a `transformer_directive`. Use the directive to describe how the ExpertActionTransformer should "
			"be invoked for high-resolution planning. Include any crucial parameters it must receive.\n\n"
			"Telemetry context (ordered timesteps):\n"
			f"{json.dumps(context_window, indent=2, ensure_ascii=False)}\n\n"
			f"Future horizon hint ({prediction_steps} steps available): {prediction_steps}"
		)

		assistant_payload = {
			"coaching_summary": directive["reason"],
			"transformer_directive": {
				"action": "invoke",
				"model": directive["model"],
				"inputs": {
					"reuse_context_window": True,
					"expected_outputs": directive["expected_outputs"],
					"future_hint": directive.get("future_hint", []),
				},
				"metadata": directive.get("metadata", {}),
			},
		}

		return PromptResponseExample(
			prompt=user_prompt,
			response=json.dumps(assistant_payload, ensure_ascii=False),
			system_prompt=self._system_prompt,
			metadata={
				"provider": self.name,
				"prediction_steps": prediction_steps,
				"source": metadata,
			},
		)

	@staticmethod
	def _variance(values: Any) -> float:
		if not values:
			return 0.0
		mean = sum(values) / len(values)
		return float(sum((value - mean) ** 2 for value in values) / len(values))


__all__ = [
	"LLMTrainingContext",
	"LLMTrainingContribution",
	"BaseLLMTrainingProvider",
	"SegmentExplanationTrainingProvider",
	"TransformerDirectiveTrainingProvider",
	"PromptResponseExample",
]
