"""
Simple Corner Identification Service for Track Learning

This service learns track corner layout from multiple laps and identifies
which corner and phase the driver is currently in.
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Any, Tuple, Optional
from datetime import datetime
from scipy.signal import savgol_filter
from enum import Enum

from sklearn.preprocessing import StandardScaler
from hmmlearn.hmm import GaussianHMM


class CornerFeatureCatalog:
    """Feature catalog for corner identification output."""
    
    class ContextFeature(str, Enum):
        """Corner context feature keys for output."""
        CURRENT_CORNER_NUMBER = 'current_corner_number'
        CURRENT_PHASE = 'current_phase'
        IS_IN_CORNER = 'is_in_corner'
        CORNER_PHASE_PROGRESS = 'corner_phase_progress'

    # List of all context features
    CONTEXT_FEATURES: List[str] = [f.value for f in ContextFeature]


class CornerIdentificationUnsupervisedService:
    """
    Simple corner identification service that learns track layout and identifies current position.
    
    1. Learn track corner layout from multiple laps
    2. Identify which corner and phase driver is currently in
    """
    
    def __init__(self):
        """Initialize the corner identification service."""
        self.corner_patterns = []  # Store learned track map
        self.track_corner_profiles = {}
        self.corner_model: Optional[Dict[str, Any]] = None
        self._corner_model_params: Dict[str, Any] = {}
        self._feature_names: List[str] = []
        
        # Corner detection parameters
        self.min_corner_duration = 30  # Minimum data points for a valid corner
        self.smoothing_window = 7  # Window size for smoothing telemetry data
        
        # Serialization cache
        self._last_serialized: Optional[Dict[str, Any]] = None

    def _normalize_steering(self, steering_series: pd.Series) -> pd.Series:
        """Normalize steering angle to -1..1 range."""
        s = steering_series.fillna(0.0)
        return s.clip(-1.0, 1.0)

    def _compute_enhanced_features(self, df: pd.DataFrame, global_max_speed: Optional[float] = None) -> pd.DataFrame:
        """Compute enhanced telemetry features for unsupervised corner detection."""
        if df.empty:
            return pd.DataFrame()

        features = pd.DataFrame(index=df.index)

        # Base signals with safe defaults
        steering_raw = df.get('Physics_steer_angle', pd.Series(0.0, index=df.index))
        steering_norm = self._normalize_steering(steering_raw)
        steering_smooth = pd.Series(self._smooth_signal(steering_norm), index=df.index)

        brake_raw = df.get('Physics_brake', pd.Series(0.0, index=df.index)).fillna(0.0).clip(0.0, 1.0)
        brake_smooth = pd.Series(self._smooth_signal(brake_raw), index=df.index)

        gas_raw = df.get('Physics_gas', pd.Series(0.0, index=df.index)).fillna(0.0).clip(0.0, 1.0)
        gas_smooth = pd.Series(self._smooth_signal(gas_raw), index=df.index)

        speed_kmh = df.get('Physics_speed_kmh', pd.Series(0.0, index=df.index)).ffill().fillna(0.0)
        
        if global_max_speed is not None:
            max_s = max(1.0, global_max_speed)
        else:
            max_s = max(1.0, float(speed_kmh.max()))
            
        speed_norm = speed_kmh / max_s

        yaw_signal = None
        for yaw_key in ['Physics_yaw', 'Physics_world_yaw', 'Graphics_yaw']:
            if yaw_key in df.columns:
                yaw_signal = df[yaw_key].ffill().bfill()
                break
        if yaw_signal is None:
            yaw_signal = steering_smooth
        yaw_rate = yaw_signal.diff().fillna(0.0)

        track_position = self._build_position_series(df)

        # Feature set for HMM
        features['abs_steering'] = steering_smooth.abs()
        features['steering_rate'] = steering_smooth.diff().fillna(0.0)
        features['brake'] = brake_smooth
        features['brake_rate'] = brake_smooth.diff().fillna(0.0)
        features['gas'] = gas_smooth
        features['gas_rate'] = gas_smooth.diff().fillna(0.0)
        features['speed_norm'] = speed_norm.clip(0.0, 1.5)
        features['yaw_rate'] = yaw_rate
        features['lateral_acc'] = features['abs_steering'] * features['speed_norm']
        features['longitudinal_change'] = speed_norm.diff().fillna(0.0)
        features['track_position'] = track_position

        # Replace any NaNs generated by diff/smoothing
        features = features.fillna(0.0)

        # Keep ordered feature names for model training
        self._feature_names = [
            'abs_steering',
            'steering_rate',
            'brake',
            'brake_rate',
            'gas',
            'gas_rate',
            'speed_norm',
            'yaw_rate',
            'lateral_acc',
            'longitudinal_change',
        ]

        return features

    def _prepare_hmm_training_data(
        self,
        feature_df: pd.DataFrame,
        lap_slices: List[Tuple[int, int]]
    ) -> Optional[Tuple[List[pd.DataFrame], List[int], np.ndarray]]:
        """Prepare per-lap feature sequences for HMM training."""
        if feature_df.empty or not lap_slices:
            return None

        lap_feature_frames: List[pd.DataFrame] = []
        lengths: List[int] = []
        combined_rows: List[np.ndarray] = []

        for lap_id, (lap_start, lap_end) in enumerate(lap_slices):
            if lap_end - lap_start < self.min_corner_duration:
                continue

            lap_frame = feature_df.iloc[lap_start:lap_end].copy()
            lap_frame['absolute_index'] = np.arange(lap_start, lap_end)
            lap_frame['lap_id'] = lap_id

            lap_feature_frames.append(lap_frame)
            lengths.append(len(lap_frame))
            combined_rows.append(lap_frame[self._feature_names].to_numpy())

        if not lap_feature_frames:
            return None

        combined_matrix = np.vstack(combined_rows)
        return lap_feature_frames, lengths, combined_matrix

    def _train_corner_hmm(
        self,
        lap_feature_frames: List[pd.DataFrame],
        lengths: List[int],
        combined_matrix: np.ndarray
    ) -> Optional[Tuple[GaussianHMM, StandardScaler, Dict[int, Dict[str, float]], List[int]]]:
        """Train a Gaussian HMM using the enhanced telemetry features."""

        if combined_matrix.size == 0 or not lengths:
            return None

        try:
            scaler = StandardScaler()
            scaled_matrix = scaler.fit_transform(combined_matrix)

            n_components = min(5, max(3, len(set(lengths))))
            hmm_model = GaussianHMM(
                n_components=n_components,
                covariance_type='diag',
                n_iter=200,
                tol=1e-3,
                random_state=42
            )
            hmm_model.fit(scaled_matrix, lengths)

            state_metadata = self._summarize_hmm_states(
                lap_feature_frames,
                lengths,
                scaler,
                hmm_model
            )
            corner_state_ids = self._select_corner_states(state_metadata)

            self.corner_model = {
                "hmm_model": hmm_model,
                "scaler": scaler,
                "state_metadata": state_metadata,
                "corner_state_ids": corner_state_ids,
            }

            self._corner_model_params = {
                "feature_names": list(self._feature_names),
                "hmm": {
                    "means": hmm_model.means_.tolist(),
                    "covars": hmm_model.covars_.tolist(),
                    "transmat": hmm_model.transmat_.tolist(),
                    "startprob": hmm_model.startprob_.tolist(),
                    "covariance_type": hmm_model.covariance_type,
                },
                "scaler": {
                    "mean": scaler.mean_.tolist(),
                    "scale": scaler.scale_.tolist(),
                    "n_samples_seen": int(getattr(scaler, "n_samples_seen_", combined_matrix.shape[0]))
                },
                "state_metadata": state_metadata,
                "corner_state_ids": corner_state_ids,
            }

            return hmm_model, scaler, state_metadata, corner_state_ids

        except Exception as exc:
            print(f"[WARNING] HMM training failed: {exc}")
            return None

    def _build_track_map_from_hmm(
        self,
        df: pd.DataFrame,
        feature_df: pd.DataFrame,
        lap_slices: List[Tuple[int, int]],
        lap_feature_frames: List[pd.DataFrame],
        hmm_model: GaussianHMM,
        scaler: StandardScaler,
        corner_state_ids: List[int],
        state_metadata: Dict[int, Dict[str, float]]
    ) -> List[Dict[str, Any]]:
        """Construct the track map by aggregating corner segments detected by the HMM."""

        if not corner_state_ids:
            return []

        lap_corner_segments: List[List[Dict[str, Any]]] = []
        total_laps = min(len(lap_feature_frames), len(lap_slices))

        for lap_index in range(total_laps):
            lap_frame = lap_feature_frames[lap_index]
            lap_start, lap_end = lap_slices[lap_index]
            lap_length = len(lap_frame)
            if lap_length < self.min_corner_duration:
                lap_corner_segments.append([])
                continue

            scaled = scaler.transform(lap_frame[self._feature_names])
            states = hmm_model.predict(scaled)
            lap_states = pd.Series(states, index=lap_frame.index)

            segments: List[Dict[str, Any]] = []
            current_segment = None

            for idx, state_id in enumerate(lap_states):
                is_corner_state = state_id in corner_state_ids

                if is_corner_state and current_segment is None:
                    current_segment = {
                        'start': idx,
                        'end': idx,
                        'states': [state_id]
                    }
                elif is_corner_state and current_segment is not None:
                    current_segment['end'] = idx
                    current_segment['states'].append(state_id)
                elif not is_corner_state and current_segment is not None:
                    if current_segment['end'] - current_segment['start'] >= self.min_corner_duration:
                        segments.append(current_segment)
                    current_segment = None

            if current_segment is not None and current_segment['end'] - current_segment['start'] >= self.min_corner_duration:
                segments.append(current_segment)

            lap_positions = lap_frame['track_position'].to_numpy()

            lap_corner_entries: List[Dict[str, Any]] = []
            for segment in segments:
                seg_states = segment['states']
                unique_states, counts = np.unique(seg_states, return_counts=True)
                if len(seg_states) == 0:
                    continue

                weighted_confidence = 0.0
                for state_id, cnt in zip(unique_states, counts):
                    metadata = state_metadata.get(int(state_id), {})
                    weighted_confidence += metadata.get('corner_score', 0.0) * (cnt / len(seg_states))

                seg_start_idx = segment['start']
                seg_end_idx = segment['end']

                absolute_index_series = lap_frame.get('absolute_index')
                if absolute_index_series is not None:
                    abs_start = int(absolute_index_series.iloc[seg_start_idx])
                    abs_end = int(absolute_index_series.iloc[min(seg_end_idx, lap_length - 1)])
                else:
                    abs_start = int(lap_start + seg_start_idx)
                    abs_end = int(lap_start + min(seg_end_idx, lap_length - 1))

                # Normalize positions within lap
                lap_pos_start = seg_start_idx / max(1, lap_length - 1)
                lap_pos_end = seg_end_idx / max(1, lap_length - 1)

                # Use track position signal when available for more precise alignment
                track_pos_start = float(lap_positions[min(seg_start_idx, len(lap_positions) - 1)])
                track_pos_end = float(lap_positions[min(seg_end_idx, len(lap_positions) - 1)])

                lap_corner_entries.append({
                    'lap_position_start': lap_pos_start,
                    'lap_position_end': lap_pos_end,
                    'absolute_start_idx': abs_start,
                    'absolute_end_idx': abs_end,
                    'track_pos_start': track_pos_start,
                    'track_pos_end': track_pos_end,
                    'pattern_confidence': float(np.clip(weighted_confidence, 0.05, 1.0)),
                })

            lap_corner_segments.append(lap_corner_entries)

        track_corners = self._find_consistent_corners(lap_corner_segments)

        track_map: List[Dict[str, Any]] = []
        for corner_number, corner_info in enumerate(track_corners, start=1):
            phases = self._define_corner_phases(corner_info, df)
            track_map.append({
                'corner_number': corner_number,
                'track_position_start': corner_info['position_start'],
                'track_position_end': corner_info['position_end'],
                'phases': phases,
                'examples': corner_info['examples'],
                'state_metadata': state_metadata,
            })

        return track_map

    def _summarize_hmm_states(
        self,
        lap_feature_frames: List[pd.DataFrame],
        lengths: List[int],
        scaler: StandardScaler,
        hmm_model: GaussianHMM
    ) -> Dict[int, Dict[str, float]]:
        """Summarize feature statistics for each HMM state."""

        total_samples = sum(lengths)
        state_accumulators: Dict[int, Dict[str, float]] = {}

        for lap_frame in lap_feature_frames:
            scaled = scaler.transform(lap_frame[self._feature_names])
            states = hmm_model.predict(scaled)
            lap_frame = lap_frame.copy()
            lap_frame['state'] = states

            for state_id in np.unique(states):
                mask = states == state_id
                segment = lap_frame.loc[mask]
                count = int(mask.sum())
                if count == 0:
                    continue

                accumulator = state_accumulators.setdefault(state_id, {
                    'count': 0,
                    'sum_abs_steering': 0.0,
                    'sum_brake': 0.0,
                    'sum_gas': 0.0,
                    'sum_speed': 0.0,
                    'sum_lateral_acc': 0.0,
                    'sum_yaw_rate': 0.0,
                })

                accumulator['count'] += count
                accumulator['sum_abs_steering'] += float(segment['abs_steering'].sum())
                accumulator['sum_brake'] += float(segment['brake'].sum())
                accumulator['sum_gas'] += float(segment['gas'].sum())
                accumulator['sum_speed'] += float(segment['speed_norm'].sum())
                accumulator['sum_lateral_acc'] += float(segment['lateral_acc'].sum())
                accumulator['sum_yaw_rate'] += float(segment['yaw_rate'].abs().sum())

        state_metadata: Dict[int, Dict[str, float]] = {}
        for state_id, accumulator in state_accumulators.items():
            count = max(1, accumulator['count'])
            mean_abs_steering = accumulator['sum_abs_steering'] / count
            mean_brake = accumulator['sum_brake'] / count
            mean_gas = accumulator['sum_gas'] / count
            mean_speed = accumulator['sum_speed'] / count
            mean_lateral = accumulator['sum_lateral_acc'] / count
            mean_yaw_rate = accumulator['sum_yaw_rate'] / count

            corner_score = (
                0.6 * mean_abs_steering +
                0.2 * mean_lateral +
                0.1 * mean_brake +
                0.1 * min(mean_yaw_rate, 1.0)
            )

            state_metadata[state_id] = {
                'samples': count,
                'dwell_ratio': count / max(1, total_samples),
                'mean_abs_steering': mean_abs_steering,
                'mean_brake': mean_brake,
                'mean_gas': mean_gas,
                'mean_speed_norm': mean_speed,
                'mean_lateral_acc': mean_lateral,
                'mean_yaw_rate': mean_yaw_rate,
                'corner_score': corner_score,
                'phase_label': 'straight',
            }

        return state_metadata

    def _select_corner_states(self, state_metadata: Dict[int, Dict[str, float]]) -> List[int]:
        """Select which HMM states represent corner behaviour."""
        if not state_metadata:
            return []

        # Sort states by steering intensity (proxy for cornering load)
        sorted_states = sorted(
            state_metadata.items(),
            key=lambda item: item[1]['mean_abs_steering'],
            reverse=True
        )

        if not sorted_states:
            return []

        # Assign phase labels heuristically based on braking and throttle usage
        assigned_labels: Dict[str, bool] = {'apex': False, 'turn_in': False, 'exit': False}

        for state_id, stats in sorted_states:
            if not assigned_labels['apex']:
                state_metadata[state_id]['phase_label'] = 'apex'
                assigned_labels['apex'] = True
                continue

            brake = stats['mean_brake']
            gas = stats['mean_gas']

            if brake >= gas and not assigned_labels['turn_in']:
                state_metadata[state_id]['phase_label'] = 'turn_in'
                assigned_labels['turn_in'] = True
            elif gas > brake and not assigned_labels['exit']:
                state_metadata[state_id]['phase_label'] = 'exit'
                assigned_labels['exit'] = True
            else:
                state_metadata[state_id]['phase_label'] = 'straight'

        # Any remaining unassigned states default to straight
        for state_id, stats in state_metadata.items():
            stats.setdefault('phase_label', 'straight')

        corner_state_ids = [
            state_id
            for state_id, stats in state_metadata.items()
            if stats['phase_label'] in {'apex', 'turn_in', 'exit'} or stats['corner_score'] >= 0.2
        ]

        if not corner_state_ids:
            # Ensure at least the strongest state is treated as a corner
            corner_state_ids = [sorted_states[0][0]]
            state_metadata[corner_state_ids[0]]['phase_label'] = 'apex'

        return corner_state_ids

    def _to_python(self, obj: Any) -> Any:
        """Convert numpy/pandas types to Python types for JSON serialization."""
        if isinstance(obj, (str, int, float, bool)) or obj is None:
            return obj
        if isinstance(obj, (list, tuple)):
            return [self._to_python(x) for x in obj]
        if isinstance(obj, dict):
            return {str(k): self._to_python(v) for k, v in obj.items()}
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if hasattr(obj, 'item') and callable(getattr(obj, 'item')):
            try:
                return obj.item()
            except Exception:
                return str(obj)
        return str(obj)

    def _restore_corner_model(self, params: Dict[str, Any]) -> None:
        """Restore cached HMM corner model from serialized parameters."""
        try:
            hmm_params = params.get("hmm")
            scaler_params = params.get("scaler")
            feature_names = params.get("feature_names", [])
            state_metadata = params.get("state_metadata", {})
            corner_state_ids = params.get("corner_state_ids", [])

            if not hmm_params or not scaler_params:
                raise ValueError("Incomplete model parameters")

            n_components = len(hmm_params.get("means", []))
            covariance_type = hmm_params.get("covariance_type", "diag")

            hmm_model = GaussianHMM(n_components=n_components, covariance_type=covariance_type)
            hmm_model.means_ = np.array(hmm_params["means"], dtype=float)
            hmm_model.covars_ = np.array(hmm_params["covars"], dtype=float)
            hmm_model.transmat_ = np.array(hmm_params["transmat"], dtype=float)
            hmm_model.startprob_ = np.array(hmm_params["startprob"], dtype=float)

            scaler = StandardScaler()
            scaler.mean_ = np.array(scaler_params["mean"], dtype=float)
            scaler.scale_ = np.array(scaler_params["scale"], dtype=float)
            scaler.var_ = scaler.scale_ ** 2
            scaler.n_features_in_ = len(scaler.mean_)
            scaler.n_samples_seen_ = scaler_params.get("n_samples_seen", 0)

            self.corner_model = {
                "hmm_model": hmm_model,
                "scaler": scaler,
                "state_metadata": state_metadata,
                "corner_state_ids": list(corner_state_ids),
            }
            self._corner_model_params = params
            self._feature_names = list(feature_names)
        except Exception as exc:
            print(f"[WARNING] Failed to restore corner model: {exc}")
            self.corner_model = None
            self._corner_model_params = {}
            self._feature_names = []

    def serialize_corner_identification_model(self) -> Dict[str, Any]:
        """Serialize the learned corner model for saving."""
        try:
            model_key = f"corner_model_{int(datetime.now().timestamp())}"
            
            payload = {
                "model_version": "1.0",
                "model_key": model_key,
                "export_timestamp": datetime.now().isoformat(),
                "corner_patterns": self._to_python(self.corner_patterns),
                "track_corner_profiles": self._to_python(self.track_corner_profiles),
                "model_parameters": self._to_python(self._corner_model_params),
                "total_corners": len(self.corner_patterns),
                "feature_catalog": list(CornerFeatureCatalog.CONTEXT_FEATURES),
                "config": {
                    "min_corner_duration": self.min_corner_duration,
                    "smoothing_window": self.smoothing_window
                },
                "has_learned_patterns": len(self.corner_patterns) > 0,
                "has_hmm_model": bool(self._corner_model_params)
            }
            
            self._last_serialized = payload
            return payload
            
        except Exception as e:
            print(f"[ERROR] Failed to serialize model: {str(e)}")
            return {
                "model_version": "1.0",
                "error": str(e),
                "corner_patterns": [],
                "total_corners": 0
            }

    def deserialize_corner_identification_model(self, payload: Dict[str, Any]) -> 'CornerIdentificationUnsupervisedService':
        """Deserialize and restore the corner model."""
        try:
            print(f"[INFO] Deserializing corner identification model...")
            
            if not isinstance(payload, dict):
                raise ValueError("Payload must be a dictionary")
            
            if "error" in payload:
                print(f"[WARNING] Payload contains error: {payload['error']}")
                return self
            
            # Restore configuration
            if "config" in payload:
                config = payload["config"]
                self.min_corner_duration = config.get("min_corner_duration", self.min_corner_duration)
                self.smoothing_window = config.get("smoothing_window", self.smoothing_window)
            
            # Restore corner patterns
            self.corner_patterns = payload.get("corner_patterns", [])
            self.track_corner_profiles = payload.get("track_corner_profiles", {})
            model_params = payload.get("model_parameters")
            if model_params:
                self._restore_corner_model(model_params)
            else:
                self.corner_model = None
                self._corner_model_params = {}
                self._feature_names = []
            
            # Cache the payload
            self._last_serialized = payload
            total_corners = len(self.corner_patterns)
            
            print(f"[INFO] Successfully deserialized model:")
            print(f"       - Total Corners: {total_corners}")
            
            return self
            
        except Exception as e:
            print(f"[ERROR] Failed to deserialize model: {str(e)}")
            self.corner_patterns = []
            self.track_corner_profiles = {}
            self._last_serialized = None
            return self
        
    async def learn_track_corner_patterns(self, laps_data: List[List[Dict[str, Any]]]) -> Dict[str, Any]:
        """
        Learn track corner layout from multiple laps.
        
        Args:
            laps_data: List of laps, where each lap is a list of telemetry records
            
        Returns:
            Dictionary with track layout learning results
        """
        try:
            print(f"[INFO] Learning track layout from {len(laps_data)} laps")
            
            if not laps_data:
                return {
                    "success": False,
                    "error": "No lap data provided",
                    "track_map": []
                }
            
            if len(laps_data) < 2:
                return {
                    "success": False,
                    "error": "Need at least 2 laps to learn track layout",
                    "track_map": []
                }
            
            # Calculate global max speed for consistent normalization
            global_max_speed = 1.0
            for lap_records in laps_data:
                if not lap_records: continue
                temp_df = pd.DataFrame(lap_records)
                if 'Physics_speed_kmh' in temp_df:
                    m = temp_df['Physics_speed_kmh'].max()
                    if pd.notna(m) and m > global_max_speed:
                        global_max_speed = float(m)
            
            # Process each lap individually to compute features correctly
            all_raw_dfs = []
            all_feature_dfs = []
            lap_slices = []
            current_idx = 0
            
            for lap_records in laps_data:
                if not lap_records:
                    continue
                    
                lap_df = pd.DataFrame(lap_records)
                # Compute features per lap to avoid boundary artifacts
                lap_features = self._compute_enhanced_features(lap_df, global_max_speed=global_max_speed)
                
                n_samples = len(lap_df)
                lap_slices.append((current_idx, current_idx + n_samples))
                current_idx += n_samples
                
                all_raw_dfs.append(lap_df)
                all_feature_dfs.append(lap_features)
            
            if not all_feature_dfs:
                return {
                    "success": False,
                    "error": "No valid lap data found",
                    "track_map": []
                }
                
            # Concatenate for HMM processing
            df = pd.concat(all_raw_dfs, ignore_index=True)
            feature_df = pd.concat(all_feature_dfs, ignore_index=True)
            
            print(f"[INFO] Processed {len(lap_slices)} laps with total {len(df)} samples")
            
            hmm_inputs = self._prepare_hmm_training_data(feature_df, lap_slices)
            if hmm_inputs is None:
                return {
                    "success": False,
                    "error": "Unable to prepare data for HMM training",
                    "track_map": []
                }

            (lap_feature_frames,
             lengths,
             combined_matrix) = hmm_inputs

            hmm_result = self._train_corner_hmm(lap_feature_frames, lengths, combined_matrix)
            if not hmm_result:
                return {
                    "success": False,
                    "error": "HMM training failed",
                    "track_map": []
                }

            hmm_model, scaler, state_metadata, corner_state_ids = hmm_result
            track_map = self._build_track_map_from_hmm(
                df,
                feature_df,
                lap_slices,
                lap_feature_frames,
                hmm_model,
                scaler,
                corner_state_ids,
                state_metadata
            )

            if not track_map:
                return {
                    "success": False,
                    "error": "No corners detected",
                    "track_map": []
                }

            self.track_corner_profiles['active_model'] = {
                'model_type': 'gaussian_hmm',
                'feature_names': list(self._feature_names),
                'state_metadata': state_metadata,
                'corner_state_ids': corner_state_ids,
                'last_trained_samples': combined_matrix.shape[0],
                'lap_count': len(lengths),
            }
            
            # Store the learned track map
            self.corner_patterns = track_map
            
            print(f"[INFO] Learned {len(track_map)} corners")
            for i, corner in enumerate(track_map, 1):
                pos_start = corner['track_position_start']
                pos_end = corner['track_position_end']
                phases = len(corner['phases'])
                print(f"  Corner {i}: {pos_start:.3f} -> {pos_end:.3f} ({phases} phases)")
            
            return {
                "success": True,
                "total_corners": len(track_map),
                "track_map": track_map
            }
            
        except Exception as e:
            raise Exception(f"[ERROR] Failed to learn track: {str(e)}")
    
    async def extract_corner_features_for_telemetry(self, telemetry_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Identify which corner and phase the driver is currently in.

        Args:
            telemetry_data: List of telemetry records

        Returns:
            List of corner/phase identification for each record
        """
        try:
            if not self.corner_patterns:
                print("[ERROR] No track map available. Run learn_track_corner_patterns first.")
                return [{} for _ in range(len(telemetry_data))]
            
            df = pd.DataFrame(telemetry_data)
            position_series = self._build_position_series(df)
            
            feature_only_data = []
            
            for i in range(len(df)):
                current_position = position_series.iloc[i] if i < len(position_series) else 0.0
                corner_info = self._identify_current_corner_and_phase(current_position)
                
                # Use CornerFeatureCatalog for consistent feature naming
                CF = CornerFeatureCatalog.ContextFeature
                feature_record = {
                    CF.CURRENT_CORNER_NUMBER.value: corner_info['corner_number'],
                    CF.CURRENT_PHASE.value: corner_info['phase'],
                    CF.IS_IN_CORNER.value: 1.0 if corner_info['corner_number'] > 0 else 0.0,
                    CF.CORNER_PHASE_PROGRESS.value: corner_info['phase_progress']
                }
                
                feature_only_data.append(feature_record)

            print(f"[INFO] Identified corner/phase for {len(feature_only_data)} records")
            return feature_only_data
            
        except Exception as e:
            print(f"[ERROR] Failed to extract corner features: {str(e)}")
            return [{} for _ in range(len(telemetry_data))]

    def _smooth_signal(self, signal: pd.Series) -> np.ndarray:
        """Smooth a signal using appropriate filter."""
        signal_array = signal.values
        if len(signal_array) >= self.smoothing_window:
            return savgol_filter(signal_array, self.smoothing_window, 2)
        else:
            return pd.Series(signal_array).rolling(window=3, center=True).mean().bfill().ffill().values

    def _find_consistent_corners(self, lap_corner_data: List[List[Dict]]) -> List[Dict[str, Any]]:
        """Find corners that appear consistently across laps."""
        if not lap_corner_data:
            return []
            
        # Use lap with most corners as reference
        reference_lap = max(lap_corner_data, key=len)
        consistent_corners = []
        
        for ref_corner in reference_lap:
            ref_position = (ref_corner['lap_position_start'] + ref_corner['lap_position_end']) / 2
            
            # Find matching corners in other laps
            matching_corners = [ref_corner]
            
            for lap_corners in lap_corner_data:
                if lap_corners is reference_lap:
                    continue
                
                # Find closest corner
                best_match = None
                best_distance = float('inf')
                
                for corner in lap_corners:
                    corner_position = (corner['lap_position_start'] + corner['lap_position_end']) / 2
                    distance = abs(corner_position - ref_position)
                    
                    if distance < best_distance and distance <= 0.05:  # 5% tolerance
                        best_distance = distance
                        best_match = corner
                
                if best_match:
                    matching_corners.append(best_match)
            
            # Require corner in at least 70% of laps
            if len(matching_corners) >= max(2, int(len(lap_corner_data) * 0.7)):
                # Average position
                avg_start = sum(c['lap_position_start'] for c in matching_corners) / len(matching_corners)
                avg_end = sum(c['lap_position_end'] for c in matching_corners) / len(matching_corners)
                
                consistent_corners.append({
                    'position_start': avg_start,
                    'position_end': avg_end,
                    'examples': matching_corners
                })
        
        # Sort by position
        consistent_corners.sort(key=lambda x: x['position_start'])
        return consistent_corners

    def _define_corner_phases(self, corner_info: Dict[str, Any], df: pd.DataFrame) -> List[Dict[str, Any]]:
        """Define phases for a corner."""
        if not corner_info['examples']:
            return []
        
        example = corner_info['examples'][0]
        start_idx = example['absolute_start_idx']
        end_idx = example['absolute_end_idx']
        
        corner_df = df.iloc[start_idx:end_idx+1]
        
        if len(corner_df) < 6:
            return [{
                'phase': 'corner',
                'position_start': corner_info['position_start'],
                'position_end': corner_info['position_end']
            }]
        
        # Find apex (minimum speed)
        speeds = corner_df['Physics_speed_kmh'].ffill().bfill()
        apex_idx = speeds.idxmin()
        apex_relative = (apex_idx - corner_df.index[0]) / len(corner_df)
        
        # Define phases
        phases = []
        
        # Turn-in phase
        turn_in_end = min(0.4, apex_relative - 0.1)
        if turn_in_end > 0.1:
            phases.append({
                'phase': 'turn_in',
                'position_start': corner_info['position_start'],
                'position_end': corner_info['position_start'] + (corner_info['position_end'] - corner_info['position_start']) * turn_in_end
            })
        
        # Apex phase
        apex_start = max(turn_in_end, apex_relative - 0.15)
        apex_end = min(1.0, apex_relative + 0.15)
        
        phases.append({
            'phase': 'apex',
            'position_start': corner_info['position_start'] + (corner_info['position_end'] - corner_info['position_start']) * apex_start,
            'position_end': corner_info['position_start'] + (corner_info['position_end'] - corner_info['position_start']) * apex_end
        })
        
        # Exit phase
        if apex_end < 0.9:
            phases.append({
                'phase': 'exit',
                'position_start': corner_info['position_start'] + (corner_info['position_end'] - corner_info['position_start']) * apex_end,
                'position_end': corner_info['position_end']
            })
        
        return phases

    def _identify_current_corner_and_phase(self, track_position: float) -> Dict[str, Any]:
        """Identify current corner and phase."""
        result = {
            'corner_number': 0,
            'phase': 'straight',
            'phase_progress': 0.0
        }
        
        for corner in self.corner_patterns:
            corner_start = corner['track_position_start']
            corner_end = corner['track_position_end']
            
            # Check if in this corner
            if corner_start <= track_position <= corner_end:
                result['corner_number'] = corner['corner_number']
                
                # Find current phase
                for phase in corner['phases']:
                    phase_start = phase['position_start']
                    phase_end = phase['position_end']
                    
                    if phase_start <= track_position <= phase_end:
                        result['phase'] = phase['phase']
                        # Calculate progress within phase
                        phase_length = phase_end - phase_start
                        if phase_length > 0:
                            result['phase_progress'] = (track_position - phase_start) / phase_length
                        break
                break
        
        return result



    def _build_position_series(self, df: pd.DataFrame) -> pd.Series:
        """Build 0..1 position series for a lap."""
        n = len(df)
        if n == 0:
            return pd.Series([], dtype=float)
        
        if 'Graphics_normalized_car_position' in df.columns:
            pos = df['Graphics_normalized_car_position'].ffill().bfill()
            return pos.clip(0.0, 1.0).reset_index(drop=True)
        
        # Fallback to linear interpolation
        return pd.Series(np.linspace(0.0, 1.0, n)).reset_index(drop=True)

    def clear_corner_cache(self):
        """Clear cached corner identification models."""
        self.track_corner_profiles.clear()
        self.corner_patterns.clear()
        self._last_serialized = None
        print(f"[INFO] Cleared corner identification cache")
        
    def get_corner_model_summary(self) -> Dict[str, Any]:
        """Get summary of loaded corner identification models."""
        return {
            "model_type": "corner_identification",
            "cached_models": len(self.track_corner_profiles),
            "available_models": list(self.track_corner_profiles.keys()),
            "corner_patterns_count": len(self.corner_patterns),
            "has_active_patterns": len(self.corner_patterns) > 0,
            "feature_catalog": CornerFeatureCatalog.CONTEXT_FEATURES
        }

    def export_corner_patterns(self) -> Dict[str, Any]:
        """Export current corner patterns for external saving."""
        return {
            "corner_patterns": self.corner_patterns,
            "track_corner_profiles": self.track_corner_profiles,
            "export_timestamp": datetime.now().isoformat(),
            "feature_catalog": CornerFeatureCatalog.CONTEXT_FEATURES
        }


# Create service instance
corner_identification_service = CornerIdentificationUnsupervisedService()