services:
  frontend-image:
    build: ./acla_front
    container_name: acla_front_c
    ports:
      - '3000:3000'
    # Mounts the current directory and node_modules for hot-reloading.
    volumes:
      - ./acla_front:/app_volumes

    # stdin_open and tty: Keep the container running and interactive.
    stdin_open: true
    tty: true

  backend-image:
    build: ./acla_backend
    container_name: acla_backend_c
    ports:
      - '4000:4000'
