services:
  frontend:
    build:
      context: ./acla_front
      dockerfile: dev.dockerfile
    container_name: acla_front_c
    env_file:
      - .dev.env
    environment:
       - WATCHPACK_POLLING=true
       - WDS_SOCKET_PORT=3000
       - FAST_REFRESH=false
    ports:
      - '${REACT_WEBSITE_PORT}:3000'
    # Mounts the current directory and node_modules for hot-reloading.
    volumes:
      - ./acla_front:/app
      - /app/node_modules
    # stdin_open and tty: Keep the container running and interactive.
    stdin_open: true
    tty: true
    depends_on:
      - backend_proxy

  backend_proxy:
    image: nginx:stable-perl
    container_name: backend_proxy_c
    ports:
      - "${REACT_APP_BACKEND_PROXY_PORT}:80"
    volumes:
      - ./backend_nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    build:
      context: ./acla_backend
      dockerfile: dev.dockerfile
    container_name: acla_backend_c
    env_file:
      - .dev.env
    volumes:
      - ./acla_backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    ports:
      - '7001:7001'
    networks:
      - db-network
      - frontend-network

  mongodb:
    build: ./acla_db
    container_name: mongodb_c
    restart: always
    environment:
      #create a user for authticated database access
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMINUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMINPASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATEBASE}
    volumes:
      - ./acla_db/Init.js:/docker-entrypoint-initdb.d/Init.js:ro
      - ./acla_db/mongodb_data:/data/db
    env_file:
      - .dev.env
    ports:
      - "27017:27017"
    networks:
      - db-network

  #The default values for the first login are "admin" for username and "pass" for password
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .dev.env
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      #use the created admin user inside this compose file for authenticated database access
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMINUSERNAME}:${MONGO_ADMINPASSWORD}@mongodb_c:27017
    volumes:
      - ./acla_db/mongodb_data:/data/db
    networks:
      - db-network
    depends_on:
      - mongodb

networks:
  db-network:
    driver: bridge

  frontend-network:
    driver: bridge
