services:
  ai_service:
    build:
      context: ./acla_ai_service
      dockerfile: dev.cpu.dockerfile
  ai_training:
    build:
      context: .
      dockerfile: acla_ai_training/dev.cpu.dockerfile
