"""Behavioural label catalog (ID → display name) and grouping metadata.

Pure data: dicts indexed by short label ID. No behaviour, no imports
from any framework or service. Moved from app/models/segment_models.py
in refactor/hexagonal-v1, Step 3.
"""

from typing import Any, Dict, List


def normalize_label_id(label: Any) -> str:
    return str(label)


def normalize_label_ids(labels: Any) -> List[str]:
    if not isinstance(labels, list):
        return []

    normalized: List[str] = []
    seen = set()
    for label in labels:
        current = normalize_label_id(label)
        if current not in seen:
            normalized.append(current)
            seen.add(current)
    return normalized


LABEL_MAPPING: Dict[str, str] = {
    ################### Main Labels ###################
    "O": "Successful Overtake",
    "OD": "Successful Defense",
    "EA": "Expert Adherence (Training)",
    "PS": "Pit Stop",
    
    "RM": "Recovery & Merge",
    "MSP": "Mistake (Practice)",
    "MSR": "Mistake (Racing)",
    ################### Detailed Expert Adherence (Training) Labels (for label EA) ###################

    ################### Detailed Successful Overtake Labels (for label O) ###################
    "O1": "Late-brake attack at entry",
    "O3": "Outside-line sweep",
    "O4": "Switchback",
    "O5": "Slipstream gain on straight",

    ################### Detailed Pit Stop Labels (for label PS) ###################
    "PS1": "Exit pit lane",
    
    ################### Detailed Successful Defense Labels (for label OD) ###################
    "OD1": "Inside cover (early-brake defense)",
    "OD2": "Defensive lift on straight",
    ################### Detailed Recovery & Merge Labels (for label RM) ###################
    "RM1": "Recover from off-track",
    "RM5": "Recover from speed gap over 20",
    "RM6": "Recover from small speed gap under 20",
    "RM7": "Merge back to expert line",
    "RM8": "Accelerate eariler at exit",
    "RM9": "Accelerate later at exit",
    "RM10": "Brake earlier at entry",
    "RM11": "Brake later at entry",
    ################### Detailed Practice-Mistake Labels (for label MSP) — technical errors, opponent-agnostic ###################
    "MSP1": "Initiate brake too late",
    "MSP2": "Initiate the turn too late",
    "MSP3": "Too late compared to expert Apex",
    "MSP4": "time to exit too early",
    "MSP5": "Initiate brake too early",
    "MSP6": "Initiate the turn too early",
    "MSP7": "Too early compared to expert Apex",
    "MSP8": "time to exit too late",
    "MSP9": "Entry trajectory too tight",
    "MSP10": "Apex too wide",
    "MSP11": "Exit trajectory too narrow",
    "MSP13": "Highest Brake pressure too low",
    "MSP14": "Brake applied too quickly",
    "MSP15": "Throttle applied too quickly",
    "MSP16": "Exit trajectory too wide",
    "MSP17": "Release brake too quickly",
    "MSP18": "Release brake too slowly",
    "MSP19": "Highest throttle pressure too low",
    "MSP20": "Initiate throttle too early",
    "MSP21": "Initiate throttle too late",
    "MSP22": "Highest Brake pressure too high",
    "MSP23": "Release throttle too quickly",
    "MSP24": "Brake applied too slowly",
    "MSP25": "Throttle applied too slowly",
    "MSP26": "Highest throttle pressure too high",
    "MSP27": "Initiate brake release too late",
    "MSP28": "Initiate brake release too early",
    "MSP29": "Initiate throttle release too late",
    "MSP30": "Initiate throttle release too early",
    "MSP31": "Highest Brake length too short",
    "MSP32": "Highest Brake length too long",
    "MSP33": "Entry trajectory too wide",
    "MSP34": "Throttle and brake applied at the same time for too long",
    "MSP35": "Shift up too early",
    "MSP36": "Shift up too late",
    "MSP37": "Shift down too early",
    "MSP38": "Shift down too late",
    "MSP41": "Cutting the line",
    "MSP42": "Inefficient grip utilization at entry",
    "MSP43": "Inefficient grip utilization at exit",
    "MSP44": "Oversteering at entry",
    "MSP45": "Understeering at entry",
    "MSP46": "Oversteering at exit",
    "MSP47": "Understeering at exit",
    "MSP48": "Gear Too low when accelerating",
    "MSP49": "Gear Too high when accelerating",
    "MSP50": "Off track at entry",
    "MSP51": "Off track at exit",
    "MSP52": "Off track in the straight",
    ################### Detailed Racing-Mistake Labels (for label MSR) — interaction-failure with a close opponent ###################
    "MSR1": "Failed overtake attempt (type unclear)",
    "MSR2": "Defense broken (type unclear)",
    "MSR3": "Failed late-brake attack at entry",
    "MSR4": "Failed outside-line sweep",
    "MSR5": "Failed switchback",
    "MSR6": "Failed slipstream gain on straight",
    "MSR7": "Inside cover broken (early-brake defense)",
    "MSR8": "Defensive lift broken on straight",
              ################### Corner name ###################
    "brands_hatch":"Brands Hatch",
    "brands_hatch1":"Brabham Straight",
    "brands_hatch2":"Paddock Hill Bend",
    "brands_hatch3":"Druids",
    "brands_hatch4":"Graham Hill Bend",
    "brands_hatch5":"Cooper Straight",
    "brands_hatch6":"Surtees",
    "brands_hatch7":"Pilgrim's Drop",
    "brands_hatch9":"Hawthorns",
    "brands_hatch10":"Derek Minter Straight",
    "brands_hatch11":"Westfield Bend",
    "brands_hatch12":"Dingle Dell",
    "brands_hatch13":"Sheene Curve",
    "brands_hatch14":"Stirlings",
    "brands_hatch15":"Clearways",
    "brands_hatch16":"Clark Curve",
    "brands_hatch17":"Pit",
    "brands_hatch18":"Graham Hill",
    "brands_hatch19":"Hailwoods Hill",

    "silverstone":"Silverstone",
    "silverstone1":"Woodcote",
    "silverstone2":"Copse",
    "silverstone3":"Maggotts first turn",
    "silverstone4":"Magotts second turn",
    "silverstone5":"Becketts first turn",
    "sliverstone6":"Becketts second turn",
    "silverstone6":"Chapel",
    "silverstone7":"Hangar Straight",
    "silverstone8":"Stowe",
    "silverstone9":"Vale",
    "silverstone10":"Club first turn",
    "silverstone11":"Club second turn",
    "silverstone12":"Hamilton Straight",
    "silverstone13":"Abbey",
    "silverstone14":"Farm Curve",
    "silverstone15":"Village",
    "silverstone16":"The Loop",
    "silverstone17":"Aintree",
    "silverstone18":"Wellington Straight",
    "silverstone19":"Brooklands",
    "silverstone20":"Luffield",
    "silverstone21":"Pit",

    "moza":"Moza",
    "moza1":"Straight between 1 Varinate and Curva Parabolica",
    "moza2":"1 Varinate 1st turn",
    "moza3":"1 Varinate 2nd turn",
    "moza4": "Curva Biassono",
    "moza5": "2 Varinate",
    "moza6": "Curve di Lesmo first curve",
    "moza7": "Curve di Lesmo second curve",
    "moza8": "Curva del Serraglio",
    "moza9": "Variante Ascari 1st turn",
    "moza10": "Variante Ascari 2nd turn",
    "moza11": "Variante Ascari 3rd turn",
    "moza12": "Straight between Variante Ascari and Curva Parabolica",
    "moza13": "Curva Parabolica",
    "moza14": "Pit",

    #Kyalami
    "kyalami":"Kyalami",
    "kyalami1":"The Kink",
    "kyalami2":"Crowthorne",
    "kyalami3":"Jukskei Sweep 1st turn",
    "kyalami4":"Jukskei Sweep 2nd turn",
    "kyalami5":"Barbeque",
    "kyalami6":"Sunset",
    "kyalami7":"Clubhouse",
    "kyalami8":"The Esses 1st turn",
    "kyalami9":"The Esses 2nd turn",
    "kyalami10":"Leeukop 1st turn",
    "kyalami11":"Leeukop 2nd turn",
    "kyalami12":"Mineshaft",
    "kyalami13":"The Crocodiles",
    "kyalami14":"Cheetah",
    "kyalami15":"Ingwe",
    "kyalami16":"Pit",

    #Suzuka
    "suzuka":"Suzuka",
    "suzuka1":"First Curve 1st turn",
    "suzuka2":"First Curve 2nd turn",
    "suzuka3":"S Curve 1st turn",
    "suzuka4":"S Curve 2nd turn",
    "suzuka5":"S Curve 3rd turn",
    "suzuka6":"S Curve 4th turn",
    "suzuka7":"S Curve 5th turn",
    "suzuka8":"Dunlop Corner",
    "suzuka9":"Degner Curve",
    "suzuka10":"Hairpin",
    "suzuka11":"200R",
    "suzuka12":"Spoon Curve 1st turn",
    "suzuka13":"Spoon Curve 2nd turn",
    "suzuka14":"Backstretch",
    "suzuka15":"130R",
    "suzuka16":"Casio Triangle 1st turn",
    "suzuka17":"Casio Triangle 2nd turn",
    "suzuka18":"Last Curve",
    "suzuka19":"Pit",

    #Laguna_Seca
    "laguna_seca":"Laguna Seca",
    "laguna_seca1":"Turn 1",
    "laguna_seca2":"Andretti Hairpin",
    "laguna_seca3":"Turn 3",
    "laguna_seca4":"Turn 4",
    "laguna_seca5":"Turn 5",
    "laguna_seca6":"Turn 6",
    "laguna_seca7":"Rahal Straight",
    "laguna_seca8":"Turn 7",
    "laguna_seca9":"Corkscrew 1st turn",
    "laguna_seca10":"Corkscrew 2nd turn",
    "laguna_seca11":"Rainey Curve",
    "laguna_seca12":"Turn 10",
    "laguna_seca13":"Turn 11",
    "laguna_seca14":"Pit",

    #mount_panorama
    "mount_panorama":"Mount Panorama",
    "mount_panorama1":"Hell Corner",
    "mount_panorama2":"Mountain Straight",
    "mount_panorama3":"Quarry Corner",
    "mount_panorama4":"The Cutting 1st turn",
    "mount_panorama5":"The Cutting 2nd turn",
    "mount_panorama6":"Griffins Bend",
    "mount_panorama7":"Reid Park 1st turn",
    "mount_panorama8":"Reid Park 2nd turn",
    "mount_panorama9":"Sulman Park",
    "mount_panorama10":"McPhillamy Park",
    "mount_panorama11":"Skyline",
    "mount_panorama12":"The Esses 1st turn",
    "mount_panorama13":"The Esses 2nd turn",
    "mount_panorama14":"The Dipper 1st turn",
    "mount_panorama15":"The Dipper 2nd turn",
    "mount_panorama16":"Forrest's Elbow",
    "mount_panorama17":"Conrod Straight",
    "mount_panorama18":"The Chase 1st turn",
    "mount_panorama19":"The Chase 2nd turn",
    "mount_panorama20":"The Chase 3rd turn",
    "mount_panorama21":"Murray's Corner",
    "mount_panorama22":"Pit Straight",

    #watkins_glen
    "watkins_glen":"Watkins Glen",
    "watkins_glen1":"The Ninety",
    "watkins_glen2":"The Esses 1st turn",
    "watkins_glen3":"The Esses 2nd turn",
    "watkins_glen4":"The Esses 3rd turn",
    "watkins_glen5":"Back Straight",
    "watkins_glen6":"Inner Loop 1st turn",
    "watkins_glen7":"Inner Loop 2nd turn",
    "watkins_glen8":"Inner Loop 3rd turn",
    "watkins_glen9":"Inner Loop 4th turn",
    "watkins_glen10":"Outer Loop",
    "watkins_glen11":"Chute",
    "watkins_glen12":"Laces",
    "watkins_glen13":"Toe",
    "watkins_glen14":"Heel",
    "watkins_glen15":"Turn 9",
    "watkins_glen16":"Turn 10",
    "watkins_glen17":"Turn 11",
    "watkins_glen18":"Pit",

    #indianapolis
    "indianapolis":"Indianapolis",
    "indianapolis1":"Turn 1",
    "indianapolis2":"Turn 2",
    "indianapolis3":"Turn 3",
    "indianapolis4":"Turn 4",
    "indianapolis5":"Turn 5",
    "indianapolis6":"Turn 6",
    "indianapolis7":"Hulman Blvd. Straight",
    "indianapolis8":"Turn 7",
    "indianapolis9":"Turn 8",
    "indianapolis10":"Turn 9",
    "indianapolis11":"Turn 10",
    "indianapolis12":"Turn 11",
    "indianapolis13":"Turn 12",
    "indianapolis14":"Turn 13",
    "indianapolis15":"Turn 14",
    "indianapolis16":"Front Straight \ Pit",

    #cota
    "cota":"Circuit of the Americas",
    "cota1":"Straight between Turns 1 and 21",
    "cota2":"Turn 1",
    "cota3":"Turn 2",
    "cota4":"Turn 3",
    "cota5":"Turn 4",
    "cota6":"Turn 5",
    "cota7":"Turn 6",
    "cota8":"Turn 7",
    "cota9":"Turn 8",
    "cota10":"Turn 9",
    "cota11":"Turn 10",
    "cota12":"Turn 11",
    "cota13": "Straight between Turns 11 and 12",
    "cota14":"Turn 12",
    "cota15":"Turn 13 and turn 14",
    "cota16":"Turn 15",
    "cota17":"Turn 16, 17 and 18",
    "cota18":"Turn 19",
    "cota19":"Turn 20",
    "cota20":"Pit Straight",

    
    ################### Segment Type ###################
    "ST1": "In the corner",
    "ST2": "On the straight",
    "ST3": "Approach to corner",
    "ST4": "Exit corner leading to straight",
    "ST5": "Between consecutive corners",
    "ST6": "Consecutive corners with no straight in between",
    "ST7": "Constant-radius corner",
    "ST8": "Increasing-radius corner",
    "ST9": "Decreasing-radius corner",
    "ST10": "Hairpin corner",
    "ST11": "Chicane or esses",
    "ST12": "Entry altitude uphill",
    "ST13": "Entry altitude level",
    "ST14": "Entry altitude downhill",
    "ST15": "Apex altitude uphill",
    "ST16": "Apex altitude level",
    "ST17": "Apex altitude downhill",
    "ST18": "Exit altitude uphill",
    "ST19": "Exit altitude level",
    "ST20": "Exit altitude downhill",
}
LABEL_NAME_TO_ID: Dict[str, str] = {v: k for k, v in LABEL_MAPPING.items()}

LABEL_IMAGE_MAP: Dict[str, str] = {
    "brands_hatch": "Brands_Hatch_2003.jpg",
    "silverstone": "Silverstone_Circuit_2020.jpg"
}

BEHAVIOR_LABELS: List[str] = ["O", "OD", "EA", "PS", "RM", "MSP", "MSR"]

TRACK_LABELS: List[str] = [
    "brands_hatch",
    "silverstone",
    "moza",
    "kyalami",
    "suzuka",
    "laguna_seca",
    "mount_panorama",
    "watkins_glen",
    "indianapolis",
    "cota",
]

LABEL_CATEGORIES: Dict[str, List[str]] = {
    "Main Labels": BEHAVIOR_LABELS + ["brands_hatch","silverstone","kyalami","suzuka","watkins_glen","indianapolis","cota"],
    "Behavior": BEHAVIOR_LABELS,
    "Track": TRACK_LABELS,
    "O":["O1","O3","O4","O5"],
    "OD":["OD1","OD2"],
    "EA":[],
    "PS":["PS1"],
    "RM":["RM1", "RM5","RM6","RM7","RM8","RM9","RM10","RM11"],
    "brands_hatch":["brands_hatch1","brands_hatch2","brands_hatch3","brands_hatch4","brands_hatch5","brands_hatch6","brands_hatch7","brands_hatch8","brands_hatch9","brands_hatch10","brands_hatch11","brands_hatch12","brands_hatch13","brands_hatch14","brands_hatch15","brands_hatch16","brands_hatch17","brands_hatch18","brands_hatch19"],
    "silverstone":["silverstone1","silverstone2","silverstone3","silverstone4","silverstone5","silverstone6","silverstone7","silverstone8","silverstone9","silverstone10","silverstone11","silverstone12","silverstone13","silverstone14","silverstone15","silverstone16","silverstone17","silverstone18","silverstone19","silverstone20","silverstone21"],
    "moza":["moza1","moza2","moza3","moza4","moza5","moza6","moza7","moza8","moza9","moza10","moza11","moza12","moza13","moza14"],
    "kyalami":["kyalami1","kyalami2","kyalami3","kyalami4","kyalami5","kyalami6","kyalami7","kyalami8","kyalami9","kyalami10","kyalami11","kyalami12","kyalami13","kyalami14","kyalami15","kyalami16"],
    "suzuka":["suzuka1","suzuka2","suzuka3","suzuka4","suzuka5","suzuka6","suzuka7","suzuka8","suzuka9","suzuka10","suzuka11","suzuka12","suzuka13","suzuka14","suzuka15","suzuka16","suzuka17","suzuka18","suzuka19"],
    "laguna_seca":["laguna_seca1","laguna_seca2","laguna_seca3","laguna_seca4","laguna_seca5","laguna_seca6","laguna_seca7","laguna_seca8","laguna_seca9","laguna_seca10","laguna_seca11","laguna_seca12","laguna_seca13","laguna_seca14"],
    "mount_panorama":["mount_panorama1","mount_panorama2","mount_panorama3","mount_panorama4","mount_panorama5","mount_panorama6","mount_panorama7","mount_panorama8","mount_panorama9","mount_panorama10","mount_panorama11","mount_panorama12","mount_panorama13","mount_panorama14","mount_panorama15","mount_panorama16","mount_panorama17","mount_panorama18","mount_panorama19","mount_panorama20","mount_panorama21","mount_panorama22",],
    "watkins_glen":["watkins_glen1","watkins_glen2","watkins_glen3","watkins_glen4","watkins_glen5","watkins_glen6","watkins_glen7","watkins_glen8","watkins_glen9","watkins_glen10","watkins_glen11","watkins_glen12","watkins_glen13","watkins_glen14","watkins_glen15","watkins_glen16","watkins_glen17"],
    "indianapolis":["indianapolis1","indianapolis2","indianapolis3","indianapolis4","indianapolis5","indianapolis6","indianapolis7","indianapolis8","indianapolis9","indianapolis10","indianapolis11","indianapolis12","indianapolis13","indianapolis14","indianapolis15","indianapolis16"],
    "cota":["cota1","cota2","cota3","cota4","cota5","cota6","cota7","cota8","cota9","cota10","cota11","cota12","cota13","cota14","cota15","cota16","cota17","cota18","cota19","cota20"],
    "MSP":["MSP1","MSP2","MSP3","MSP4","MSP5","MSP6","MSP7","MSP8","MSP9","MSP10","MSP11","MSP13","MSP14","MSP15","MSP16","MSP17","MSP18","MSP19","MSP20","MSP21","MSP22","MSP23","MSP24","MSP25","MSP26","MSP27","MSP28","MSP29","MSP30","MSP31","MSP32","MSP33","MSP34","MSP35","MSP36","MSP37","MSP38","MSP41","MSP42","MSP43","MSP44","MSP45","MSP46","MSP47","MSP48","MSP49","MSP50","MSP51","MSP52"],
    "MSR":["MSR1","MSR2","MSR3","MSR4","MSR5","MSR6","MSR7","MSR8"],
    "Segment Type": ["ST1", "ST2", "ST3", "ST4", "ST5", "ST6", "ST7", "ST8", "ST9", "ST10", "ST11", "ST12", "ST13", "ST14", "ST15", "ST16", "ST17", "ST18", "ST19", "ST20"]
}


__all__ = [
    "LABEL_MAPPING",
    "LABEL_NAME_TO_ID",
    "LABEL_IMAGE_MAP",
    "BEHAVIOR_LABELS",
    "TRACK_LABELS",
    "LABEL_CATEGORIES",
    "normalize_label_id",
    "normalize_label_ids",
]
