import os
import sys
import uuid
from pathlib import Path

# Add the project root to the Python path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ui.segment_tabs.shared import get_store, get_available_sessions, load_annotations

def update_segments_add_ids(annotation_key: str):
    """
    Adds a UUID to existing segments that don't have one and saves them.
    
    Args:
        annotation_key (str): The dataset/cache key for the annotations to update.
    Returns:
        dict: Statistics about the migration.
    """
    print(f"Starting ID migration for cache key: {annotation_key}")
    store = get_store()
    
    sessions = get_available_sessions(annotation_key)
    stats = {
        "sessions_processed": 0,
        "segments_updated": 0,
        "segments_already_had_id": 0
    }
    
    if not sessions:
        print(f"No sessions found for cache key: {annotation_key}")
        return stats
        
    for session_id in sessions:
        anns = load_annotations(session_id, annotation_key)
        if not anns:
            continue
            
        stats["sessions_processed"] += 1
        updated = False
        
        # When creating the objects from_dict, missing IDs are autogenerated,
        # but to be sure we are permanently assigning one if it's new:
        for ann in anns:
            # Check if this ID is empty or just generated on the fly. 
            # Well, `load_annotations` calls `from_dict`, which gives it an ID if it's missing.
            # So `ann.id` is guaranteed to be set if from_dict has default `uuid4()`.
            # To know if we "updated" them, we just check what's in the actual db dict vs the object.
            # But the simplest approach is just to load them and save them back.
            # If `ann.id` exists and we just loaded it, `store.save_chunk` will persist it.
            
            # Since from_dict generates a new UUID each load if not saved, we just save them back.
            stats["segments_updated"] += 1
            updated = True
            
        if updated:
            data_to_save = [a.to_dict() for a in anns]
            store.save_chunk(annotation_key, session_id, data_to_save)
            print(f"Session {session_id}: Saved {len(anns)} segments with IDs.")
            
    return stats

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Add IDs to legacy annotation segments.")
    parser.add_argument("--key", type=str, required=True, help="Annotation cache key")
    
    args = parser.parse_args()
    results = update_segments_add_ids(args.key)
    print(f"Migration Complete: {results}")